apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: mongodb2-pvc 
spec: 
  storageClassName: ultra-fast-ssd
  resources: 
    requests:
      storage: 1Gi 
  accessModes:
  - ReadWriteOnce
