apiVersion: v1
kind: Service
metadata:
    name: nodesjs-sfs-lb
spec:
    type: LoadBalancer
    ports:
    - port: {{ .Values.lb.port }}
      targetPort: {{ .Values.lb.targetPort }}
    selector:
        app: nodejs-sfs