apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-standard-retain
provisioner: kubernetes.io/gce-pd
reclaimPolicy: {{ Values.sc.reclaimPolicy }}
parameters:
  type: {{ Values.sc.type }}
  zone: {{ Values.sc.zone }}