apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.sts.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  serviceName: {{ .Values.container.name }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}
        ports:
        - name: http
          containerPort: {{ .Values.container.port }}
        volumeMounts:
        - name: {{ .Values.container.volumeName }}
          mountPath: {{ .Values.container.volumePath}}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.volumeClaim.name}}
    spec:
      resources:
        requests:
          storage: {{ .Values.volumeClaim.storageSize }}
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ .Values.volumeClaim.class }}